#Pytorch 2-2

In [2]:
import torch

t=torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [3]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [3]:
print(t[0], t[-1])
print(t[2:5])

tensor(0.) tensor(6.)
tensor([2., 3., 4.])


In [4]:
t=torch.FloatTensor([[1., 2., 3], [4., 5., 6.], [7., 8., 9.], [10., 11., 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [5]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [6]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [8]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [9]:
m1=torch.FloatTensor([[3, 3]])
m2=torch.FloatTensor([[2, 2]])
print(m1+m2)

tensor([[5., 5.]])


In [10]:
m1=torch.FloatTensor([[1, 2]])
m2=torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [11]:
m1=torch.FloatTensor([[1, 2]])
m2=torch.FloatTensor([[3], [4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [4]:
m1=torch.FloatTensor([[1, 2], [3, 4]])
m2=torch.FloatTensor([[1], [2]])
print(m1*m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [5]:
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [8]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [10]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [12]:
print(t.max())
print(t.max(dim=0))
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


#Pytorch 2-3

In [14]:
import numpy as np

t=np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
ft=torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [17]:
print(ft.view(-1, 3))
print(ft.view(-1, 1, 3))
print(ft.view(-1, 1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [18]:
ft=torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [5]:
import torch
lt=torch.LongTensor([1, 2, 3, 4])
bt=torch.ByteTensor([True, False, True, False])
print(lt)
print(lt.float())
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 1, 0], dtype=torch.uint8)
tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


In [10]:
x=torch.FloatTensor([1, 4])
y=torch.FloatTensor([2, 5])
z=torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
x=torch.IntTensor([[0, 1, 2], [3, 4, 5]])
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


#3-1 선형회귀

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [14]:
torch.manual_seed(1)

In [16]:
x_train=torch.FloatTensor([[1], [2], [3]])
y_train=torch.FloatTensor([[2], [4], [6]])

In [17]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [18]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [19]:
W=torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [21]:
b=torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [22]:
H=x_train*W+b
print(H)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [25]:
C=torch.mean((H-y_train)**2)
print(C)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [27]:
optimizer=optim.SGD([W, b], lr=0.01)

In [30]:
epoch=1999

In [33]:
for i in range(epoch+1):
  H=x_train*W+b

  C=torch.mean((H-y_train)**2)

  optimizer.zero_grad()
  C.backward()
  optimizer.step()

  if i%100==0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(i, epoch, W.item(), b.item(), C.item()))

Epoch    0/1999 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/1999 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/1999 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/1999 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/1999 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/1999 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/1999 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.000 Cost: 0.000000


In [1]:
import torch
w=torch.tensor(2.0, requires_grad=True)
print(w)
epoch=20
for i in range(epoch+1):
  z=2*w
  z.backward()
  print(w.grad)

tensor(2., requires_grad=True)
tensor(2.)
tensor(4.)
tensor(6.)
tensor(8.)
tensor(10.)
tensor(12.)
tensor(14.)
tensor(16.)
tensor(18.)
tensor(20.)
tensor(22.)
tensor(24.)
tensor(26.)
tensor(28.)
tensor(30.)
tensor(32.)
tensor(34.)
tensor(36.)
tensor(38.)
tensor(40.)
tensor(42.)


#3-2 자동 미분

In [2]:
import torch

w=torch.tensor(2.0, requires_grad=True)
y=w**2
z=2*y+5

z.backward()
print(w.grad)

tensor(8.)


#3-3 다중 선형 회귀

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x1_train=torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [4]:
w1=torch.zeros(1, requires_grad=True)
w2=torch.zeros(1, requires_grad=True)
w3=torch.zeros(1, requires_grad=True)
b=torch.zeros(1, requires_grad=True)

In [6]:
optimizer=optim.SGD([w1, w2, w3, b], lr=1e-5)
epoch=1000

In [9]:
for i in range(epoch+1):
  H=w1*x1_train+w2*x2_train+w3*x3_train+b
  C=torch.mean((H-y_train)**2)

  optimizer.zero_grad()
  C.backward()
  optimizer.step()

  if i%100==0:
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            i, epoch, w1.item(), w2.item(), w3.item(), b.item(), C.item()
        ))

Epoch    0/1000 w1: 0.551 w2: 0.550 w3: 0.557 b: 0.006 Cost: 2915.712402
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.562267
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.496319
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.433817
Epoch  400/1000 w1: 0.690 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.374578
Epoch  500/1000 w1: 0.695 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.318401
Epoch  600/1000 w1: 0.699 w2: 0.632 w3: 0.679 b: 0.009 Cost: 1.265181
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.214727
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.166880
Epoch  900/1000 w1: 0.714 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.121539
Epoch 1000/1000 w1: 0.718 w2: 0.612 w3: 0.680 b: 0.009 Cost: 1.078544


#다중 선형 회귀 - 내적

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

X_train=torch.FloatTensor([[73, 80, 75], [93, 88, 93], [89, 91, 90], [96, 98, 100], [73, 66, 70]])
Y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

W=torch.zeros((3, 1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

optimizer=optim.SGD([W, b], lr=1e-5)

epoch=1000

for i in range(epoch+1):
  H=X_train.matmul(W)+b
  C=torch.mean((H-Y_train)**2)

  optimizer.zero_grad()
  C.backward()
  optimizer.step()

  if i%100==0:
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        i, epoch, H.squeeze().detach(), C.item()))

Epoch    0/1000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 hypothesis: tensor([152.7691, 183.6985, 180.9591, 197.0627, 140.1336]) Cost: 1.563628
Epoch  200/1000 hypothesis: tensor([152.7273, 183.7273, 180.9465, 197.0517, 140.1731]) Cost: 1.497595
Epoch  300/1000 hypothesis: tensor([152.6866, 183.7554, 180.9343, 197.0409, 140.2116]) Cost: 1.435044
Epoch  400/1000 hypothesis: tensor([152.6470, 183.7827, 180.9224, 197.0304, 140.2491]) Cost: 1.375726
Epoch  500/1000 hypothesis: tensor([152.6085, 183.8093, 180.9108, 197.0201, 140.2856]) Cost: 1.319507
Epoch  600/1000 hypothesis: tensor([152.5711, 183.8352, 180.8996, 197.0101, 140.3211]) Cost: 1.266222
Epoch  700/1000 hypothesis: tensor([152.5346, 183.8604, 180.8887, 197.0003, 140.3557]) Cost: 1.215703
Epoch  800/1000 hypothesis: tensor([152.4992, 183.8849, 180.8780, 196.9908, 140.3895]) Cost: 1.167810
Epoch  900/1000 hypothesis: tensor([152.4647, 183.9087, 180.8677, 196.9814, 140.4223]) Cost: 1.122429
Epoch 

#3-4 nn.Module 선형 회귀

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [17]:
torch.manual_seed(1)

In [18]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [19]:
model=nn.Linear(1, 1)

In [20]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [21]:
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

In [22]:
epoch=2000

for i in range(epoch+1):
  P=model(x_train)
  C=F.mse_loss(P, y_train)

  optimizer.zero_grad()
  C.backward()
  optimizer.step()

  if i % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          i, epoch, C.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch    1/2000 Cost: 10.358571
Epoch    2/2000 Cost: 8.188817
Epoch    3/2000 Cost: 6.473738
Epoch    4/2000 Cost: 5.118055
Epoch    5/2000 Cost: 4.046456
Epoch    6/2000 Cost: 3.199410
Epoch    7/2000 Cost: 2.529861
Epoch    8/2000 Cost: 2.000614
Epoch    9/2000 Cost: 1.582268
Epoch   10/2000 Cost: 1.251583
Epoch   11/2000 Cost: 0.990191
Epoch   12/2000 Cost: 0.783570
Epoch   13/2000 Cost: 0.620243
Epoch   14/2000 Cost: 0.491138
Epoch   15/2000 Cost: 0.389082
Epoch   16/2000 Cost: 0.308409
Epoch   17/2000 Cost: 0.244637
Epoch   18/2000 Cost: 0.194224
Epoch   19/2000 Cost: 0.154372
Epoch   20/2000 Cost: 0.122867
Epoch   21/2000 Cost: 0.097959
Epoch   22/2000 Cost: 0.078267
Epoch   23/2000 Cost: 0.062698
Epoch   24/2000 Cost: 0.050387
Epoch   25/2000 Cost: 0.040652
Epoch   26/2000 Cost: 0.032953
Epoch   27/2000 Cost: 0.026864
Epoch   28/2000 Cost: 0.022046
Epoch   29/2000 Cost: 0.018234
Epoch   30/2000 Cost: 0.015217
Epoch   31/2000 Cost: 0.012829
Epoch 

In [24]:
new_var=torch.FloatTensor([[4.0]])
prd=model(new_var)
print(prd)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [25]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [27]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [29]:
model=nn.Linear(3, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True), Parameter containing:
tensor([-0.0707], requires_grad=True)]


In [30]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

In [31]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 22642.416016
Epoch  100/2000 Cost: 4.976951
Epoch  200/2000 Cost: 4.733481
Epoch  300/2000 Cost: 4.502824
Epoch  400/2000 Cost: 4.284275
Epoch  500/2000 Cost: 4.077209
Epoch  600/2000 Cost: 3.881021
Epoch  700/2000 Cost: 3.695124
Epoch  800/2000 Cost: 3.519025
Epoch  900/2000 Cost: 3.352130
Epoch 1000/2000 Cost: 3.194023
Epoch 1100/2000 Cost: 3.044178
Epoch 1200/2000 Cost: 2.902206
Epoch 1300/2000 Cost: 2.767665
Epoch 1400/2000 Cost: 2.640176
Epoch 1500/2000 Cost: 2.519374
Epoch 1600/2000 Cost: 2.404892
Epoch 1700/2000 Cost: 2.296402
Epoch 1800/2000 Cost: 2.193589
Epoch 1900/2000 Cost: 2.096157
Epoch 2000/2000 Cost: 2.003828


#3-5 클래스로 모델 구현

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [40]:
class LRModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

In [41]:
class MLRModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [36]:
torch.manual_seed(1)

In [37]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [42]:
model=LRModel()

In [56]:
optimizer=optim.SGD(model.parameters(), lr=0.01)

In [54]:
epoch=2000

In [57]:
for i in range(epoch+1):
  P=model(x_train)

  C=F.mse_loss(P, y_train)

  optimizer.zero_grad()
  C.backward()
  optimizer.step()

  if i % 100 == 0:
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          i, epoch, C.item()
      ))

Epoch    0/2000 Cost: 0.000000
Epoch  100/2000 Cost: 0.000000
Epoch  200/2000 Cost: 0.000000
Epoch  300/2000 Cost: 0.000000
Epoch  400/2000 Cost: 0.000000
Epoch  500/2000 Cost: 0.000000
Epoch  600/2000 Cost: 0.000000
Epoch  700/2000 Cost: 0.000000
Epoch  800/2000 Cost: 0.000000
Epoch  900/2000 Cost: 0.000000
Epoch 1000/2000 Cost: 0.000000
Epoch 1100/2000 Cost: 0.000000
Epoch 1200/2000 Cost: 0.000000
Epoch 1300/2000 Cost: 0.000000
Epoch 1400/2000 Cost: 0.000000
Epoch 1500/2000 Cost: 0.000000
Epoch 1600/2000 Cost: 0.000000
Epoch 1700/2000 Cost: 0.000000
Epoch 1800/2000 Cost: 0.000000
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000
